export enum SourceEnrichissement {
  API_CARTO_NATURE = "ApiCartoNature",
  API_CARTO_GPU = "ApiCartoGPU",
  CADASTRE = "Cadastre",
  BDNB = "BDNB",
  BDNB_SURFACE_BATIE = "BDNB-SurfaceBatie",
  BDNB_RISQUES = "BDNB-Risques",
  ENEDIS_RACCORDEMENT = "Enedis-Raccordement",
  OVERPASS = "Overpass",
  LOVAC = "Lovac",
  GEORISQUES_RGA = "GeoRisques-RGA",
  GEORISQUES_CATNAT = "GeoRisques-CATNAT",
  GEORISQUES_TRI = "GeoRisques-TRI",
  GEORISQUES_TRI_ZONAGE = "GeoRisques-TRI-Zonage",
  GEORISQUES_MVT = "GeoRisques-MVT",
  GEORISQUES_ZONAGE_SISMIQUE = "GeoRisques-ZonageSismique",
  GEORISQUES_CAVITES = "GeoRisques-Cavites",
  GEORISQUES_OLD = "GeoRisques-OLD",
  GEORISQUES_SIS = "GeoRisques-SIS",
  GEORISQUES_ICPE = "GeoRisques-ICPE",
  GEORISQUES_AZI = "GeoRisques-AZI",
  GEORISQUES_PAPI = "GeoRisques-PAPI",
  GEORISQUES_PPR = "GeoRisques-PPR",
  SERVICE_PUBLIC = "API Service Public",
  IGN_WFS = "IGN WFS",
}
